In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("forest_fires_for_analysis_all_nuts_normalised_area.csv")

In [4]:
len(df)

41055

In [5]:
df['id'].nunique()

39774

In [6]:
# Define fire size categories
bins = [0, 5, 30, 100, 1000, 5000, 10000, float("inf")]

labels = [
    "Very small (<5 ha)",
    "Small (5-30 ha)", #until <30 and then >=30 in the next category
    "Medium (30-100 ha)",
    "Large (100-1,000 ha)",
    "Very large (1,000-5,000 ha)",
    "Extreme (5,000-10,000 ha)",
    "Mega (10,000+ ha)"
]

df["fire_size_category"] = pd.cut(
    df["area_ha"],
    bins=bins,
    labels=labels,
    right=False,
    include_lowest=True
)

df.drop(columns=['nuts_country', 'geometry_area_ha', 'total_geometry_area_ha'], inplace=True)
df

,id,country,province,commune,firedate,area_ha,broadleaved_forest_pct,coniferous_forest_pct,mixed_forest_pct,sclerophyllous_vegetation_pct,...,natural_vegetation_ha,nuts3_id,nuts3_name,nuts3_urban_rural,nuts3_mountain,nuts3_coastal,nuts2_name,nuts1_name,geometry_area_ha_normalized,fire_size_category
0,288077,IT,Salerno,Giffoni Valle Piana,2025-12-31 23:00:00+00:00,2,33.333333,0.0,0.0,0.0,...,1.333333,ITF35,Salerno,intermediate,mountain area,coastal,Campania,Sud,2.0,Very small (<5 ha)
1,288076,IT,Salerno,Giffoni Valle Piana,2025-12-31 23:00:00+00:00,2,0.000000,0.0,0.0,0.0,...,2.000000,ITF35,Salerno,intermediate,mountain area,coastal,Campania,Sud,2.0,Very small (<5 ha)
2,288108,PT,Alto Minho,Gondoriz,2025-12-31 13:12:00+00:00,1,NaN,NaN,NaN,NaN,...,NaN,PT111,Alto Minho,rural,mountain area,coastal,Norte,Continente,1.0,Very small (<5 ha)
3,288112,FR,Cantal,Saint-Cirgues-de-Jordanne,2025-12-31 12:44:00+00:00,5,0.000000,0.0,0.0,0.0,...,5.000000,FRK12,Cantal,rural,mountain area,NaN,Auvergne,Auvergne-Rhône-Alpes,5.0,Small (5-30 ha)
4,288095,FR,Cantal,Saint-Cirgues-de-Jordanne,2025-12-31 11:31:00+00:00,9,16.666667,0.0,0.0,0.0,...,7.500000,FRK12,Cantal,rural,mountain area,NaN,Auvergne,Auvergne-Rhône-Alpes,9.0,Small (5-30 ha)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41050,9109,PT,Alto Tâmega,"Cambeses do Rio, Donões e Mourilhe",2015-01-24 23:00:00+00:00,179,1.117318,0.0,0.0,0.0,...,151.000000,PT11B,Alto Tâmega e Barroso,rural,mountain area,NaN,Norte,Continente,179.0,"Large (100-1,000 ha)"
41051,9195,PT,Alto Tâmega,Montalegre e Padroso,2015-01-24 23:00:00+00:00,51,3.773585,0.0,0.0,0.0,...,49.075472,PT11B,Alto Tâmega e Barroso,rural,mountain area,NaN,Norte,Continente,51.0,Medium (30-100 ha)
41052,10658,PT,Alto Tâmega,Sezelhe e Covelães,2015-01-24 23:00:00+00:00,210,0.000000,0.0,0.0,0.0,...,203.971292,PT11B,Alto Tâmega e Barroso,rural,mountain area,NaN,Norte,Continente,210.0,"Large (100-1,000 ha)"
41053,9363,PT,Alto Tâmega,"Cambeses do Rio, Donões e Mourilhe",2015-01-14 23:00:00+00:00,51,0.000000,0.0,0.0,0.0,...,44.264151,PT11B,Alto Tâmega e Barroso,rural,mountain area,NaN,Norte,Continente,51.0,Medium (30-100 ha)
41054,9087,ES,Asturias,Santa Eulalia de Oscos,2015-01-11 23:00:00+00:00,147,43.243243,0.0,0.0,0.0,...,83.432432,ES120,Asturias,intermediate,mountain area,coastal,Principado de Asturias,Noroeste,147.0,"Large (100-1,000 ha)"

In [7]:
df['month'].value_counts()

month
March        7544
August       7026
July         5390
February     5272
September    3434
April        3276
January      2268
June         2108
October      1946
May          1158
November     1026
December      607
Name: count, dtype: int64

In [8]:
winter_season = ['January', 'February', 'March', 'November', 'December']
fire_season = ['April', 'May', 'June', 'July', 'August', 'September', 'October']

df_fire_season = df[df['month'].isin(fire_season)]
df_winter_season = df[df['month'].isin(winter_season)]

In [9]:
df_fire_season

,id,country,province,commune,firedate,area_ha,broadleaved_forest_pct,coniferous_forest_pct,mixed_forest_pct,sclerophyllous_vegetation_pct,...,natural_vegetation_ha,nuts3_id,nuts3_name,nuts3_urban_rural,nuts3_mountain,nuts3_coastal,nuts2_name,nuts1_name,geometry_area_ha_normalized,fire_size_category
194,285364,RO,Tulcea,Jurilovca,2025-10-30 23:07:00+00:00,59,0.000000,0.0,0.000000,0.0,...,59.000000,RO225,Tulcea,rural,NaN,coastal,Sud-Est,Macroregiunea Doi,59.0,Medium (30-100 ha)
195,285361,ES,Alicante/Alacant,Elche / Elx,2025-10-30 10:51:00+00:00,7,0.000000,0.0,0.000000,0.0,...,7.000000,ES521,Alicante/Alacant,urban,mountain area,coastal,Comunitat Valenciana,Este,7.0,Small (5-30 ha)
196,285343,BG,Сливен,Котел,2025-10-30 09:32:00+00:00,1,0.000000,0.0,0.000000,0.0,...,1.000000,BG342,Сливен,intermediate,mountain area,NaN,Югоизточен,Северна и Югоизточна България,1.0,Very small (<5 ha)
197,286183,ES,Cantabria,Corvera de Toranzo,2025-10-29 12:23:00+00:00,11,0.000000,0.0,0.000000,0.0,...,11.000000,ES130,Cantabria,intermediate,mountain area,coastal,Cantabria,Noroeste,11.0,Small (5-30 ha)
198,286284,IT,Foggia,Carpino,2025-10-29 10:40:00+00:00,2,0.000000,0.0,0.000000,0.0,...,2.000000,ITF46,Foggia,urban,NaN,coastal,Puglia,Sud,2.0,Very small (<5 ha)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40992,9123,PT,Alto Tâmega,Ardãos e Bobadela,2015-04-02 22:00:00+00:00,103,0.000000,0.0,0.000000,0.0,...,103.000000,PT11B,Alto Tâmega e Barroso,rural,mountain area,NaN,Norte,Continente,103.0,"Large (100-1,000 ha)"
40993,319,PT,Área Metropolitana do Porto,Tropeço,2015-04-01 22:00:00+00:00,490,3.271984,0.0,15.337423,0.0,...,354.723926,PT11A,Área Metropolitana do Porto,urban,NaN,coastal,Norte,Continente,490.0,"Large (100-1,000 ha)"
40994,155,PT,Alto Tâmega,Outeiro,2015-04-01 22:00:00+00:00,105,0.000000,0.0,0.000000,0.0,...,105.000000,PT11B,Alto Tâmega e Barroso,rural,mountain area,NaN,Norte,Continente,105.0,"Large (100-1,000 ha)"
40995,819,PT,Região de Aveiro,Albergaria-a-Velha e Valmaior,2015-04-01 22:00:00+00:00,1711,8.231173,0.0,0.000000,0.0,...,1481.268535,PT191,Região de Aveiro,intermediate,NaN,coastal,Centro (PT),Continente,1711.0,"Very large (1,000-5,000 ha)"
40996,7163,PT,Alto Tâmega,Alturas do Barroso e Cerdedo,2015-04-01 22:00:00+00:00,66,0.000000,0.0,0.000000,0.0,...,39.794118,PT11B,Alto Tâmega e Barroso,rural,mountain area,NaN,Norte,Continente,66.0,Medium (30-100 ha)

In [10]:
df_fire_season['id'].nunique()

23391

In [11]:
float_cols = df_fire_season.select_dtypes(include="float").columns

df_fire_season[float_cols] = df_fire_season[float_cols].round(2)
df_fire_season

,id,country,province,commune,firedate,area_ha,broadleaved_forest_pct,coniferous_forest_pct,mixed_forest_pct,sclerophyllous_vegetation_pct,...,natural_vegetation_ha,nuts3_id,nuts3_name,nuts3_urban_rural,nuts3_mountain,nuts3_coastal,nuts2_name,nuts1_name,geometry_area_ha_normalized,fire_size_category
194,285364,RO,Tulcea,Jurilovca,2025-10-30 23:07:00+00:00,59,0.00,0.0,0.00,0.0,...,59.00,RO225,Tulcea,rural,NaN,coastal,Sud-Est,Macroregiunea Doi,59.0,Medium (30-100 ha)
195,285361,ES,Alicante/Alacant,Elche / Elx,2025-10-30 10:51:00+00:00,7,0.00,0.0,0.00,0.0,...,7.00,ES521,Alicante/Alacant,urban,mountain area,coastal,Comunitat Valenciana,Este,7.0,Small (5-30 ha)
196,285343,BG,Сливен,Котел,2025-10-30 09:32:00+00:00,1,0.00,0.0,0.00,0.0,...,1.00,BG342,Сливен,intermediate,mountain area,NaN,Югоизточен,Северна и Югоизточна България,1.0,Very small (<5 ha)
197,286183,ES,Cantabria,Corvera de Toranzo,2025-10-29 12:23:00+00:00,11,0.00,0.0,0.00,0.0,...,11.00,ES130,Cantabria,intermediate,mountain area,coastal,Cantabria,Noroeste,11.0,Small (5-30 ha)
198,286284,IT,Foggia,Carpino,2025-10-29 10:40:00+00:00,2,0.00,0.0,0.00,0.0,...,2.00,ITF46,Foggia,urban,NaN,coastal,Puglia,Sud,2.0,Very small (<5 ha)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40992,9123,PT,Alto Tâmega,Ardãos e Bobadela,2015-04-02 22:00:00+00:00,103,0.00,0.0,0.00,0.0,...,103.00,PT11B,Alto Tâmega e Barroso,rural,mountain area,NaN,Norte,Continente,103.0,"Large (100-1,000 ha)"
40993,319,PT,Área Metropolitana do Porto,Tropeço,2015-04-01 22:00:00+00:00,490,3.27,0.0,15.34,0.0,...,354.72,PT11A,Área Metropolitana do Porto,urban,NaN,coastal,Norte,Continente,490.0,"Large (100-1,000 ha)"
40994,155,PT,Alto Tâmega,Outeiro,2015-04-01 22:00:00+00:00,105,0.00,0.0,0.00,0.0,...,105.00,PT11B,Alto Tâmega e Barroso,rural,mountain area,NaN,Norte,Continente,105.0,"Large (100-1,000 ha)"
40995,819,PT,Região de Aveiro,Albergaria-a-Velha e Valmaior,2015-04-01 22:00:00+00:00,1711,8.23,0.0,0.00,0.0,...,1481.27,PT191,Região de Aveiro,intermediate,NaN,coastal,Centro (PT),Continente,1711.0,"Very large (1,000-5,000 ha)"
40996,7163,PT,Alto Tâmega,Alturas do Barroso e Cerdedo,2015-04-01 22:00:00+00:00,66,0.00,0.0,0.00,0.0,...,39.79,PT11B,Alto Tâmega e Barroso,rural,mountain area,NaN,Norte,Continente,66.0,Medium (30-100 ha)

In [12]:
unique_fires = df_fire_season.drop_duplicates(subset="id")
unique_fires

,id,country,province,commune,firedate,area_ha,broadleaved_forest_pct,coniferous_forest_pct,mixed_forest_pct,sclerophyllous_vegetation_pct,...,natural_vegetation_ha,nuts3_id,nuts3_name,nuts3_urban_rural,nuts3_mountain,nuts3_coastal,nuts2_name,nuts1_name,geometry_area_ha_normalized,fire_size_category
194,285364,RO,Tulcea,Jurilovca,2025-10-30 23:07:00+00:00,59,0.00,0.0,0.00,0.0,...,59.00,RO225,Tulcea,rural,NaN,coastal,Sud-Est,Macroregiunea Doi,59.0,Medium (30-100 ha)
195,285361,ES,Alicante/Alacant,Elche / Elx,2025-10-30 10:51:00+00:00,7,0.00,0.0,0.00,0.0,...,7.00,ES521,Alicante/Alacant,urban,mountain area,coastal,Comunitat Valenciana,Este,7.0,Small (5-30 ha)
196,285343,BG,Сливен,Котел,2025-10-30 09:32:00+00:00,1,0.00,0.0,0.00,0.0,...,1.00,BG342,Сливен,intermediate,mountain area,NaN,Югоизточен,Северна и Югоизточна България,1.0,Very small (<5 ha)
197,286183,ES,Cantabria,Corvera de Toranzo,2025-10-29 12:23:00+00:00,11,0.00,0.0,0.00,0.0,...,11.00,ES130,Cantabria,intermediate,mountain area,coastal,Cantabria,Noroeste,11.0,Small (5-30 ha)
198,286284,IT,Foggia,Carpino,2025-10-29 10:40:00+00:00,2,0.00,0.0,0.00,0.0,...,2.00,ITF46,Foggia,urban,NaN,coastal,Puglia,Sud,2.0,Very small (<5 ha)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40992,9123,PT,Alto Tâmega,Ardãos e Bobadela,2015-04-02 22:00:00+00:00,103,0.00,0.0,0.00,0.0,...,103.00,PT11B,Alto Tâmega e Barroso,rural,mountain area,NaN,Norte,Continente,103.0,"Large (100-1,000 ha)"
40993,319,PT,Área Metropolitana do Porto,Tropeço,2015-04-01 22:00:00+00:00,490,3.27,0.0,15.34,0.0,...,354.72,PT11A,Área Metropolitana do Porto,urban,NaN,coastal,Norte,Continente,490.0,"Large (100-1,000 ha)"
40994,155,PT,Alto Tâmega,Outeiro,2015-04-01 22:00:00+00:00,105,0.00,0.0,0.00,0.0,...,105.00,PT11B,Alto Tâmega e Barroso,rural,mountain area,NaN,Norte,Continente,105.0,"Large (100-1,000 ha)"
40995,819,PT,Região de Aveiro,Albergaria-a-Velha e Valmaior,2015-04-01 22:00:00+00:00,1711,8.23,0.0,0.00,0.0,...,1481.27,PT191,Região de Aveiro,intermediate,NaN,coastal,Centro (PT),Continente,1711.0,"Very large (1,000-5,000 ha)"
40996,7163,PT,Alto Tâmega,Alturas do Barroso e Cerdedo,2015-04-01 22:00:00+00:00,66,0.00,0.0,0.00,0.0,...,39.79,PT11B,Alto Tâmega e Barroso,rural,mountain area,NaN,Norte,Continente,66.0,Medium (30-100 ha)

In [13]:
pd.set_option('display.max_columns', None)

In [14]:
unique_fires

,id,country,province,commune,firedate,area_ha,broadleaved_forest_pct,coniferous_forest_pct,mixed_forest_pct,sclerophyllous_vegetation_pct,transitional_woodland_shrub_pct,other_natural_land_cover_pct,agricultural_areas_pct,artificial_surfaces_pct,other_land_cover_pct,natura2000_pct,lastupdate,year,month,broadleaved_forest_ha,coniferous_forest_ha,mixed_forest_ha,sclerophyllous_vegetation_ha,transitional_woodland_shrub_ha,other_natural_land_cover_ha,agricultural_areas_ha,artificial_surfaces_ha,other_land_cover_ha,natura2000_ha,forests_ha,natural_vegetation_ha,nuts3_id,nuts3_name,nuts3_urban_rural,nuts3_mountain,nuts3_coastal,nuts2_name,nuts1_name,geometry_area_ha_normalized,fire_size_category
194,285364,RO,Tulcea,Jurilovca,2025-10-30 23:07:00+00:00,59,0.00,0.0,0.00,0.0,0.00,100.00,0.00,0.00,0.0,100.00,2025-11-03 07:23:38.485000+00:00,2025,October,0.00,0.0,0.00,0.0,0.00,59.00,0.00,0.00,0.0,59.00,0.00,59.00,RO225,Tulcea,rural,NaN,coastal,Sud-Est,Macroregiunea Doi,59.0,Medium (30-100 ha)
195,285361,ES,Alicante/Alacant,Elche / Elx,2025-10-30 10:51:00+00:00,7,0.00,0.0,0.00,0.0,0.00,100.00,0.00,0.00,0.0,100.00,2025-11-03 07:15:33.072000+00:00,2025,October,0.00,0.0,0.00,0.0,0.00,7.00,0.00,0.00,0.0,7.00,0.00,7.00,ES521,Alicante/Alacant,urban,mountain area,coastal,Comunitat Valenciana,Este,7.0,Small (5-30 ha)
196,285343,BG,Сливен,Котел,2025-10-30 09:32:00+00:00,1,0.00,0.0,0.00,0.0,0.00,100.00,0.00,0.00,0.0,100.00,2025-10-31 14:02:35.770000+00:00,2025,October,0.00,0.0,0.00,0.0,0.00,1.00,0.00,0.00,0.0,1.00,0.00,1.00,BG342,Сливен,intermediate,mountain area,NaN,Югоизточен,Северна и Югоизточна България,1.0,Very small (<5 ha)
197,286183,ES,Cantabria,Corvera de Toranzo,2025-10-29 12:23:00+00:00,11,0.00,0.0,0.00,0.0,8.33,91.67,0.00,0.00,0.0,0.00,2025-11-10 11:37:00.227000+00:00,2025,October,0.00,0.0,0.00,0.0,0.92,10.08,0.00,0.00,0.0,0.00,0.00,11.00,ES130,Cantabria,intermediate,mountain area,coastal,Cantabria,Noroeste,11.0,Small (5-30 ha)
198,286284,IT,Foggia,Carpino,2025-10-29 10:40:00+00:00,2,0.00,0.0,0.00,0.0,0.00,100.00,0.00,0.00,0.0,0.00,2025-11-11 12:16:23.427000+00:00,2025,October,0.00,0.0,0.00,0.0,0.00,2.00,0.00,0.00,0.0,0.00,0.00,2.00,ITF46,Foggia,urban,NaN,coastal,Puglia,Sud,2.0,Very small (<5 ha)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40992,9123,PT,Alto Tâmega,Ardãos e Bobadela,2015-04-02 22:00:00+00:00,103,0.00,0.0,0.00,0.0,25.47,74.53,0.00,0.00,0.0,0.00,2022-01-26 10:57:54.973000+00:00,2015,April,0.00,0.0,0.00,0.0,26.24,76.76,0.00,0.00,0.0,0.00,0.00,103.00,PT11B,Alto Tâmega e Barroso,rural,mountain area,NaN,Norte,Continente,103.0,"Large (100-1,000 ha)"
40993,319,PT,Área Metropolitana do Porto,Tropeço,2015-04-01 22:00:00+00:00,490,3.27,0.0,15.34,0.0,72.39,0.00,9.00,0.00,0.0,1.63,2022-01-26 10:57:54.973000+00:00,2015,April,16.03,0.0,75.15,0.0,354.72,0.00,44.09,0.00,0.0,8.00,91.19,354.72,PT11A,Área Metropolitana do Porto,urban,NaN,coastal,Norte,Continente,490.0,"Large (100-1,000 ha)"
40994,155,PT,Alto Tâmega,Outeiro,2015-04-01 22:00:00+00:00,105,0.00,0.0,0.00,0.0,0.00,100.00,0.00,0.00,0.0,21.93,2022-01-26 10:57:54.973000+00:00,2015,April,0.00,0.0,0.00,0.0,0.00,105.00,0.00,0.00,0.0,23.03,0.00,105.00,PT11B,Alto Tâmega e Barroso,rural,mountain area,NaN,Norte,Continente,105.0,"Large (100-1,000 ha)"
40995,819,PT,Região de Aveiro,Albergaria-a-Velha e Valmaior,2015-04-01 22:00:00+00:00,1711,8.23,0.0,0.00,0.0,86.57,0.00,2.80,2.39,0.0,17.35,2022-01-26 10:57:54.973000+00:00,2015,April,140.84,0.0,0.00,0.0,1481.27,0.00,47.94,40.95,0.0,296.80,140.84,1481.27,PT191,Região de Aveiro,intermediate,NaN,coastal,Centro (PT),Continente,1711.0,"Very large (1,000-5,000 ha)"
40996,7163,PT,Alto Tâmega,Alturas do Barroso e Cerdedo,2015-04-01 22:00:00+00:00,66,0.00,0.0,0.00,0.0,0.00,60.29,39.71,0.00,0.0,0.00,2022-01-26 10:57:54.973000+00:00,2015,April,0.00,0.0,0.00,0.0,0.00,39.79,26.21,0.00,0.0,0.00,0.00,39.79,PT11B,Alto Tâmega e Barroso,rural,mountain area,NaN,Norte,Continente,66.0,Medium (30-100 ha)

In [15]:
unique_fires.info()

<class 'pandas.DataFrame'>
Index: 23391 entries, 194 to 40996
Data columns (total 40 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   id                               23391 non-null  int64
 1   country                          23391 non-null  str
 2   province                         23391 non-null  str
 3   commune                          23391 non-null  str
 4   firedate                         23391 non-null  str
 5   area_ha                          23391 non-null  int64
 6   broadleaved_forest_pct           23001 non-null  float64
 7   coniferous_forest_pct            23001 non-null  float64
 8   mixed_forest_pct                 23001 non-null  float64
 9   sclerophyllous_vegetation_pct    23001 non-null  float64
 10  transitional_woodland_shrub_pct  23001 non-null  float64
 11  other_natural_land_cover_pct     23001 non-null  float64
 12  agricultural_areas_pct           23001 non-null  float64
 13  artificial_surfaces_pct          23001 non-null  float64
 14  other_land_cover_pct             23001 non-null  float64
 15  natura2000_pct                   23391 non-null  float64
 16  lastupdate                       23391 non-null  str
 17  year                             23391 non-null  int64
 18  month                            23391 non-null  str
 19  broadleaved_forest_ha            23001 non-null  float64
 20  coniferous_forest_ha             23001 non-null  float64
 21  mixed_forest_ha                  23001 non-null  float64
 22  sclerophyllous_vegetation_ha     23001 non-null  float64
 23  transitional_woodland_shrub_ha   23001 non-null  float64
 24  other_natural_land_cover_ha      23001 non-null  float64
 25  agricultural_areas_ha            23001 non-null  float64
 26  artificial_surfaces_ha           23001 non-null  float64
 27  other_land_cover_ha              23001 non-null  float64
 28  natura2000_ha                    23391 non-null  float64
 29  forests_ha                       23001 non-null  float64
 30  natural_vegetation_ha            23001 non-null  float64
 31  nuts3_id                         23391 non-null  str
 32  nuts3_name                       23391 non-null  str
 33  nuts3_urban_rural                23391 non-null  str
 34  nuts3_mountain                   15530 non-null  str
 35  nuts3_coastal                    17020 non-null  str
 36  nuts2_name                       23391 non-null  str
 37  nuts1_name                       23391 non-null  str
 38  geometry_area_ha_normalized      23391 non-null  float64
 39  fire_size_category               23391 non-null  category
dtypes: category(1), float64(23), int64(3), str(13)
memory usage: 7.2 MB

In [16]:
italy = unique_fires[unique_fires['country'] == 'IT']
italy

,id,country,province,commune,firedate,area_ha,broadleaved_forest_pct,coniferous_forest_pct,mixed_forest_pct,sclerophyllous_vegetation_pct,transitional_woodland_shrub_pct,other_natural_land_cover_pct,agricultural_areas_pct,artificial_surfaces_pct,other_land_cover_pct,natura2000_pct,lastupdate,year,month,broadleaved_forest_ha,coniferous_forest_ha,mixed_forest_ha,sclerophyllous_vegetation_ha,transitional_woodland_shrub_ha,other_natural_land_cover_ha,agricultural_areas_ha,artificial_surfaces_ha,other_land_cover_ha,natura2000_ha,forests_ha,natural_vegetation_ha,nuts3_id,nuts3_name,nuts3_urban_rural,nuts3_mountain,nuts3_coastal,nuts2_name,nuts1_name,geometry_area_ha_normalized,fire_size_category
198,286284,IT,Foggia,Carpino,2025-10-29 10:40:00+00:00,2,0.00,0.0,0.00,0.00,0.00,100.00,0.00,0.0,0.0,0.00,2025-11-11 12:16:23.427000+00:00,2025,October,0.00,0.0,0.0,0.00,0.0,2.00,0.00,0.0,0.0,0.00,0.00,2.00,ITF46,Foggia,urban,NaN,coastal,Puglia,Sud,2.0,Very small (<5 ha)
199,285188,IT,Matera,Irsina,2025-10-29 10:40:00+00:00,18,0.00,0.0,0.00,0.00,0.00,78.95,21.05,0.0,0.0,0.00,2025-10-31 06:57:45.108000+00:00,2025,October,0.00,0.0,0.0,0.00,0.0,14.21,3.79,0.0,0.0,0.00,0.00,14.21,ITF52,Matera,intermediate,mountain area,coastal,Basilicata,Sud,18.0,Small (5-30 ha)
208,285094,IT,Modena,Montefiorino,2025-10-27 11:04:00+00:00,1,100.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00,2025-10-30 12:46:27.748000+00:00,2025,October,1.00,0.0,0.0,0.00,0.0,0.00,0.00,0.0,0.0,0.00,1.00,0.00,ITH54,Modena,intermediate,NaN,NaN,Emilia-Romagna,Nord-Est,1.0,Very small (<5 ha)
209,285349,IT,Enna,Enna,2025-10-27 10:06:00+00:00,13,0.00,100.0,0.00,0.00,0.00,0.00,0.00,0.0,0.0,100.00,2025-11-03 06:58:45.007000+00:00,2025,October,0.00,13.0,0.0,0.00,0.0,0.00,0.00,0.0,0.0,13.00,13.00,0.00,ITG16,Enna,intermediate,mountain area,coastal,Sicilia,Isole,13.0,Small (5-30 ha)
210,285355,IT,Messina,Galati Mamertino,2025-10-26 23:56:00+00:00,24,0.00,0.0,100.00,0.00,0.00,0.00,0.00,0.0,0.0,100.00,2025-11-03 07:05:03.234000+00:00,2025,October,0.00,0.0,24.0,0.00,0.0,0.00,0.00,0.0,0.0,24.00,24.00,0.00,ITG13,Messina,intermediate,mountain area,coastal,Sicilia,Isole,24.0,Small (5-30 ha)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40922,9045,IT,Trapani,Erice,2015-06-13 22:00:00+00:00,242,2.07,0.0,0.00,31.54,0.00,24.90,41.49,0.0,0.0,49.44,2022-01-26 10:57:54.973000+00:00,2015,June,5.02,0.0,0.0,76.32,0.0,60.25,100.41,0.0,0.0,119.65,5.02,136.56,ITG11,Trapani,intermediate,NaN,coastal,Sicilia,Isole,242.0,"Large (100-1,000 ha)"
40924,9089,IT,Ottana,Ottana,2015-06-12 22:00:00+00:00,323,0.00,0.0,0.00,14.65,0.00,22.93,62.42,0.0,0.0,0.00,2022-01-26 10:57:54.973000+00:00,2015,June,0.00,0.0,0.0,47.32,0.0,74.06,201.62,0.0,0.0,0.00,0.00,121.38,ITG2E,Nuoro,rural,mountain area,coastal,Sardegna,Isole,323.0,"Large (100-1,000 ha)"
40932,163,IT,Cosenza,Aieta,2015-05-18 22:00:00+00:00,99,0.00,0.0,68.69,0.00,2.02,14.14,15.15,0.0,0.0,0.00,2022-01-26 10:57:54.973000+00:00,2015,May,0.00,0.0,68.0,0.00,2.0,14.00,15.00,0.0,0.0,0.00,68.00,16.00,ITF61,Cosenza,intermediate,mountain area,coastal,Calabria,Sud,99.0,Medium (30-100 ha)
40934,1141,IT,Siracusa,Noto,2015-05-14 22:00:00+00:00,138,0.00,0.0,0.00,98.54,0.00,0.73,0.73,0.0,0.0,68.55,2022-01-26 10:57:54.973000+00:00,2015,May,0.00,0.0,0.0,135.99,0.0,1.01,1.01,0.0,0.0,94.60,0.00,136.99,ITG19,Siracusa,urban,NaN,coastal,Sicilia,Isole,138.0,"Large (100-1,000 ha)"
40947,7555,IT,Isernia,Venafro,2015-04-21 22:00:00+00:00,59,44.07,0.0,0.00,0.00,47.46,8.47,0.00,0.0,0.0,100.00,2022-01-26 10:57:54.973000+00:00,2015,April,26.00,0.0,0.0,0.00,28.0,5.00,0.00,0.0,0.0,59.00,26.00,33.00,ITF21,Isernia,rural,mountain area,NaN,Molise,Sud,59.0,Medium (30-100 ha)

In [18]:
italy['area_ha'].sum()

np.int64(756370)

In [19]:
unique_fires['area_ha'].sum()

np.int64(4534317)

In [17]:
(9438/23391)*100

40.34885212261126

In [20]:
(756370/4534317)*100

16.68101281846858

In [21]:
italy['fire_size_category'].value_counts()

fire_size_category
Small (5-30 ha)                3817
Medium (30-100 ha)             2725
Large (100-1,000 ha)           1638
Very small (<5 ha)             1186
Very large (1,000-5,000 ha)      67
Extreme (5,000-10,000 ha)         4
Mega (10,000+ ha)                 1
Name: count, dtype: int64

In [22]:
unique_fires['fire_size_category'].value_counts()

fire_size_category
Small (5-30 ha)                8500
Medium (30-100 ha)             5862
Very small (<5 ha)             4302
Large (100-1,000 ha)           4096
Very large (1,000-5,000 ha)     497
Extreme (5,000-10,000 ha)        73
Mega (10,000+ ha)                61
Name: count, dtype: int64

In [28]:
master_yearly = (
    italy.groupby(["country", "year"])["id"]
    .nunique()
    .reset_index(name="Number of fires")
)

master_yearly

   country  year  Number of fires
0       IT  2015               64
1       IT  2016              144
2       IT  2017              781
3       IT  2018              147
4       IT  2019              400
5       IT  2020             1087
6       IT  2021             1348
7       IT  2022             1176
8       IT  2023             1231
9       IT  2024             1343
10      IT  2025             1717

In [29]:
yearly_area = (
    italy.groupby(["country", "year"])["area_ha"]
    .sum()
    .reset_index(name="Burned hectares per year")
)
yearly_area

   country  year  Burned hectares per year
0       IT  2015                      7689
1       IT  2016                     35129
2       IT  2017                    137817
3       IT  2018                     14650
4       IT  2019                     32735
5       IT  2020                     60335
6       IT  2021                    157193
7       IT  2022                     62414
8       IT  2023                    105121
9       IT  2024                     48831
10      IT  2025                     94456

In [30]:
master_y_ha = master_yearly.merge(
    yearly_area,
    on=["country", "year"],
    how="left"
)

master_y_ha

   country  year  Number of fires  Burned hectares per year
0       IT  2015               64                      7689
1       IT  2016              144                     35129
2       IT  2017              781                    137817
3       IT  2018              147                     14650
4       IT  2019              400                     32735
5       IT  2020             1087                     60335
6       IT  2021             1348                    157193
7       IT  2022             1176                     62414
8       IT  2023             1231                    105121
9       IT  2024             1343                     48831
10      IT  2025             1717                     94456

In [32]:
yearly_land_cover = (
    italy.groupby(["country", "year"])[
        [
            "natural_vegetation_ha",
            "forests_ha",
            "agricultural_areas_ha",
            "artificial_surfaces_ha",
            "other_land_cover_ha",
            "natura2000_ha"
        ]
    ]
    .sum(min_count=1)
    .reset_index()
)

yearly_land_cover

,country,year,natural_vegetation_ha,forests_ha,agricultural_areas_ha,artificial_surfaces_ha,other_land_cover_ha,natura2000_ha
0,IT,2015,5133.52,758.54,1776.89,20.04,0.00,2989.68
1,IT,2016,11187.80,5048.77,18213.23,164.21,0.00,11094.20
2,IT,2017,69218.03,36642.01,30759.69,1076.63,120.60,46843.81
3,IT,2018,7418.21,2684.04,4349.51,87.97,110.27,3579.38
4,IT,2019,17277.48,3152.24,12140.38,128.66,36.28,8483.38
5,IT,2020,30016.98,9222.40,20567.73,316.24,211.54,18078.94
6,IT,2021,67298.03,30610.87,58233.24,432.16,616.68,34061.65
7,IT,2022,30425.15,11084.46,20490.81,319.69,90.95,14899.72
8,IT,2023,51144.97,12972.93,39034.26,1273.38,686.44,30208.82
9,IT,2024,24039.03,8052.13,16554.05,129.58,41.24,12841.11
10,IT,2025,45781.84,10801.40,37082.13,343.25,422.37,26660.81

In [37]:
master_italy = master_y_ha.merge(
    yearly_land_cover,
    on=["country", "year"],
    how="left"
)

master_italy

,country,year,Number of fires,Burned hectares per year,natural_vegetation_ha,forests_ha,agricultural_areas_ha,artificial_surfaces_ha,other_land_cover_ha,natura2000_ha
0,IT,2015,64,7689,5133.52,758.54,1776.89,20.04,0.00,2989.68
1,IT,2016,144,35129,11187.80,5048.77,18213.23,164.21,0.00,11094.20
2,IT,2017,781,137817,69218.03,36642.01,30759.69,1076.63,120.60,46843.81
3,IT,2018,147,14650,7418.21,2684.04,4349.51,87.97,110.27,3579.38
4,IT,2019,400,32735,17277.48,3152.24,12140.38,128.66,36.28,8483.38
5,IT,2020,1087,60335,30016.98,9222.40,20567.73,316.24,211.54,18078.94
6,IT,2021,1348,157193,67298.03,30610.87,58233.24,432.16,616.68,34061.65
7,IT,2022,1176,62414,30425.15,11084.46,20490.81,319.69,90.95,14899.72
8,IT,2023,1231,105121,51144.97,12972.93,39034.26,1273.38,686.44,30208.82
9,IT,2024,1343,48831,24039.03,8052.13,16554.05,129.58,41.24,12841.11
10,IT,2025,1717,94456,45781.84,10801.40,37082.13,343.25,422.37,26660.81

In [40]:
master_eu_yearly = (
    unique_fires
    .groupby("year")
    .agg(
        **{
            "EU Number of fires": ("id", "nunique"),
            "EU Burned hectares": ("area_ha", "sum"),
            "EU Natural vegetation burned (ha)": (
                "natural_vegetation_ha",
                lambda x: x.sum(min_count=1)
            ),
            "EU Forests burned (ha)": (
                "forests_ha",
                lambda x: x.sum(min_count=1)
            ),
            "EU Agricultural areas burned (ha)": (
                "agricultural_areas_ha",
                lambda x: x.sum(min_count=1)
            ),
            "EU Artificial surfaces burned (ha)": (
                "artificial_surfaces_ha",
                lambda x: x.sum(min_count=1)
            ),
            "EU Other land cover burned (ha)": (
                "other_land_cover_ha",
                lambda x: x.sum(min_count=1)
            ),
            "EU Natura 2000 burned (ha)": (
                "natura2000_ha",
                lambda x: x.sum(min_count=1)
            )
        }
    )
    .reset_index()
    .rename(columns={"year": "EU Year"})
    .sort_values("EU Year")
)

master_eu_yearly

,EU Year,EU Number of fires,EU Burned hectares,EU Natural vegetation burned (ha),EU Forests burned (ha),EU Agricultural areas burned (ha),EU Artificial surfaces burned (ha),EU Other land cover burned (ha),EU Natura 2000 burned (ha)
0,2015,400,144789,104731.60,10145.69,29423.95,434.50,53.30,31038.95
1,2016,719,315657,235380.39,21816.71,54803.86,2910.73,230.34,79705.39
2,2017,1709,939059,548710.99,225847.34,151823.93,8443.98,4232.74,191045.03
3,2018,543,110343,61096.46,35909.07,11950.58,1146.86,240.05,39845.13
4,2019,874,137145,75855.84,28372.53,32077.21,587.19,252.32,43781.66
5,2020,2319,261180,163598.03,45953.86,49718.32,1211.04,693.80,88759.74
6,2021,2573,408352,184697.48,99443.67,120470.85,2911.69,790.32,105327.59
7,2022,3482,578953,321577.83,155218.89,98060.56,3514.42,546.34,215078.77
8,2023,2536,379530,190637.84,99952.33,84351.33,3481.82,1077.61,147135.68
9,2024,3506,354387,198396.75,68333.95,84640.21,2538.61,415.34,113965.91
10,2025,4730,904922,566477.07,124786.95,209087.76,3322.00,1131.23,308176.61

In [41]:
master_italy = (
    master_italy
    .merge(
        master_eu_yearly,
        left_on="year",
        right_on="EU Year",
        how="left"
    )
    .drop(columns="EU Year")
)

master_italy

,country,year,Number of fires,Burned hectares per year,natural_vegetation_ha,forests_ha,agricultural_areas_ha,artificial_surfaces_ha,other_land_cover_ha,natura2000_ha,EU Number of fires,EU Burned hectares,EU Natural vegetation burned (ha),EU Forests burned (ha),EU Agricultural areas burned (ha),EU Artificial surfaces burned (ha),EU Other land cover burned (ha),EU Natura 2000 burned (ha)
0,IT,2015,64,7689,5133.52,758.54,1776.89,20.04,0.00,2989.68,400,144789,104731.60,10145.69,29423.95,434.50,53.30,31038.95
1,IT,2016,144,35129,11187.80,5048.77,18213.23,164.21,0.00,11094.20,719,315657,235380.39,21816.71,54803.86,2910.73,230.34,79705.39
2,IT,2017,781,137817,69218.03,36642.01,30759.69,1076.63,120.60,46843.81,1709,939059,548710.99,225847.34,151823.93,8443.98,4232.74,191045.03
3,IT,2018,147,14650,7418.21,2684.04,4349.51,87.97,110.27,3579.38,543,110343,61096.46,35909.07,11950.58,1146.86,240.05,39845.13
4,IT,2019,400,32735,17277.48,3152.24,12140.38,128.66,36.28,8483.38,874,137145,75855.84,28372.53,32077.21,587.19,252.32,43781.66
5,IT,2020,1087,60335,30016.98,9222.40,20567.73,316.24,211.54,18078.94,2319,261180,163598.03,45953.86,49718.32,1211.04,693.80,88759.74
6,IT,2021,1348,157193,67298.03,30610.87,58233.24,432.16,616.68,34061.65,2573,408352,184697.48,99443.67,120470.85,2911.69,790.32,105327.59
7,IT,2022,1176,62414,30425.15,11084.46,20490.81,319.69,90.95,14899.72,3482,578953,321577.83,155218.89,98060.56,3514.42,546.34,215078.77
8,IT,2023,1231,105121,51144.97,12972.93,39034.26,1273.38,686.44,30208.82,2536,379530,190637.84,99952.33,84351.33,3481.82,1077.61,147135.68
9,IT,2024,1343,48831,24039.03,8052.13,16554.05,129.58,41.24,12841.11,3506,354387,198396.75,68333.95,84640.21,2538.61,415.34,113965.91
10,IT,2025,1717,94456,45781.84,10801.40,37082.13,343.25,422.37,26660.81,4730,904922,566477.07,124786.95,209087.76,3322.00,1131.23,308176.61

In [42]:
column_order = [
    "country",
    "year",

    "Number of fires",
    "EU Number of fires",

    "Burned hectares per year",
    "EU Burned hectares",

    "natural_vegetation_ha",
    "EU Natural vegetation burned (ha)",

    "forests_ha",
    "EU Forests burned (ha)",

    "agricultural_areas_ha",
    "EU Agricultural areas burned (ha)",

    "artificial_surfaces_ha",
    "EU Artificial surfaces burned (ha)",

    "other_land_cover_ha",
    "EU Other land cover burned (ha)",

    "natura2000_ha",
    "EU Natura 2000 burned (ha)"
]

master_italy = master_italy[column_order]

master_italy

,country,year,Number of fires,EU Number of fires,Burned hectares per year,EU Burned hectares,natural_vegetation_ha,EU Natural vegetation burned (ha),forests_ha,EU Forests burned (ha),agricultural_areas_ha,EU Agricultural areas burned (ha),artificial_surfaces_ha,EU Artificial surfaces burned (ha),other_land_cover_ha,EU Other land cover burned (ha),natura2000_ha,EU Natura 2000 burned (ha)
0,IT,2015,64,400,7689,144789,5133.52,104731.60,758.54,10145.69,1776.89,29423.95,20.04,434.50,0.00,53.30,2989.68,31038.95
1,IT,2016,144,719,35129,315657,11187.80,235380.39,5048.77,21816.71,18213.23,54803.86,164.21,2910.73,0.00,230.34,11094.20,79705.39
2,IT,2017,781,1709,137817,939059,69218.03,548710.99,36642.01,225847.34,30759.69,151823.93,1076.63,8443.98,120.60,4232.74,46843.81,191045.03
3,IT,2018,147,543,14650,110343,7418.21,61096.46,2684.04,35909.07,4349.51,11950.58,87.97,1146.86,110.27,240.05,3579.38,39845.13
4,IT,2019,400,874,32735,137145,17277.48,75855.84,3152.24,28372.53,12140.38,32077.21,128.66,587.19,36.28,252.32,8483.38,43781.66
5,IT,2020,1087,2319,60335,261180,30016.98,163598.03,9222.40,45953.86,20567.73,49718.32,316.24,1211.04,211.54,693.80,18078.94,88759.74
6,IT,2021,1348,2573,157193,408352,67298.03,184697.48,30610.87,99443.67,58233.24,120470.85,432.16,2911.69,616.68,790.32,34061.65,105327.59
7,IT,2022,1176,3482,62414,578953,30425.15,321577.83,11084.46,155218.89,20490.81,98060.56,319.69,3514.42,90.95,546.34,14899.72,215078.77
8,IT,2023,1231,2536,105121,379530,51144.97,190637.84,12972.93,99952.33,39034.26,84351.33,1273.38,3481.82,686.44,1077.61,30208.82,147135.68
9,IT,2024,1343,3506,48831,354387,24039.03,198396.75,8052.13,68333.95,16554.05,84640.21,129.58,2538.61,41.24,415.34,12841.11,113965.91
10,IT,2025,1717,4730,94456,904922,45781.84,566477.07,10801.40,124786.95,37082.13,209087.76,343.25,3322.00,422.37,1131.23,26660.81,308176.61

In [43]:
master_italy["Italy share of EU fires (%)"] = (
    master_italy["Number of fires"]
    / master_italy["EU Number of fires"]
    * 100
).round(2)

master_italy["Italy share of EU burned hectares (%)"] = (
    master_italy["Burned hectares per year"]
    / master_italy["EU Burned hectares"]
    * 100
).round(2)

master_italy["Italy share of EU natural vegetation burned (%)"] = (
    master_italy["natural_vegetation_ha"]
    / master_italy["EU Natural vegetation burned (ha)"]
    * 100
).round(2)

master_italy["Italy share of EU forests burned (%)"] = (
    master_italy["forests_ha"]
    / master_italy["EU Forests burned (ha)"]
    * 100
).round(2)

master_italy["Italy share of EU agricultural areas burned (%)"] = (
    master_italy["agricultural_areas_ha"]
    / master_italy["EU Agricultural areas burned (ha)"]
    * 100
).round(2)

master_italy["Italy share of EU artificial surfaces burned (%)"] = (
    master_italy["artificial_surfaces_ha"]
    / master_italy["EU Artificial surfaces burned (ha)"]
    * 100
).round(2)

master_italy["Italy share of EU other land cover burned (%)"] = (
    master_italy["other_land_cover_ha"]
    / master_italy["EU Other land cover burned (ha)"]
    * 100
).round(2)

master_italy["Italy share of EU Natura 2000 burned (%)"] = (
    master_italy["natura2000_ha"]
    / master_italy["EU Natura 2000 burned (ha)"]
    * 100
).round(2)

master_italy

,country,year,Number of fires,EU Number of fires,Burned hectares per year,EU Burned hectares,natural_vegetation_ha,EU Natural vegetation burned (ha),forests_ha,EU Forests burned (ha),agricultural_areas_ha,EU Agricultural areas burned (ha),artificial_surfaces_ha,EU Artificial surfaces burned (ha),other_land_cover_ha,EU Other land cover burned (ha),natura2000_ha,EU Natura 2000 burned (ha),Italy share of EU fires (%),Italy share of EU burned hectares (%),Italy share of EU natural vegetation burned (%),Italy share of EU forests burned (%),Italy share of EU agricultural areas burned (%),Italy share of EU artificial surfaces burned (%),Italy share of EU other land cover burned (%),Italy share of EU Natura 2000 burned (%)
0,IT,2015,64,400,7689,144789,5133.52,104731.60,758.54,10145.69,1776.89,29423.95,20.04,434.50,0.00,53.30,2989.68,31038.95,16.00,5.31,4.90,7.48,6.04,4.61,0.00,9.63
1,IT,2016,144,719,35129,315657,11187.80,235380.39,5048.77,21816.71,18213.23,54803.86,164.21,2910.73,0.00,230.34,11094.20,79705.39,20.03,11.13,4.75,23.14,33.23,5.64,0.00,13.92
2,IT,2017,781,1709,137817,939059,69218.03,548710.99,36642.01,225847.34,30759.69,151823.93,1076.63,8443.98,120.60,4232.74,46843.81,191045.03,45.70,14.68,12.61,16.22,20.26,12.75,2.85,24.52
3,IT,2018,147,543,14650,110343,7418.21,61096.46,2684.04,35909.07,4349.51,11950.58,87.97,1146.86,110.27,240.05,3579.38,39845.13,27.07,13.28,12.14,7.47,36.40,7.67,45.94,8.98
4,IT,2019,400,874,32735,137145,17277.48,75855.84,3152.24,28372.53,12140.38,32077.21,128.66,587.19,36.28,252.32,8483.38,43781.66,45.77,23.87,22.78,11.11,37.85,21.91,14.38,19.38
5,IT,2020,1087,2319,60335,261180,30016.98,163598.03,9222.40,45953.86,20567.73,49718.32,316.24,1211.04,211.54,693.80,18078.94,88759.74,46.87,23.10,18.35,20.07,41.37,26.11,30.49,20.37
6,IT,2021,1348,2573,157193,408352,67298.03,184697.48,30610.87,99443.67,58233.24,120470.85,432.16,2911.69,616.68,790.32,34061.65,105327.59,52.39,38.49,36.44,30.78,48.34,14.84,78.03,32.34
7,IT,2022,1176,3482,62414,578953,30425.15,321577.83,11084.46,155218.89,20490.81,98060.56,319.69,3514.42,90.95,546.34,14899.72,215078.77,33.77,10.78,9.46,7.14,20.90,9.10,16.65,6.93
8,IT,2023,1231,2536,105121,379530,51144.97,190637.84,12972.93,99952.33,39034.26,84351.33,1273.38,3481.82,686.44,1077.61,30208.82,147135.68,48.54,27.70,26.83,12.98,46.28,36.57,63.70,20.53
9,IT,2024,1343,3506,48831,354387,24039.03,198396.75,8052.13,68333.95,16554.05,84640.21,129.58,2538.61,41.24,415.34,12841.11,113965.91,38.31,13.78,12.12,11.78,19.56,5.10,9.93,11.27
10,IT,2025,1717,4730,94456,904922,45781.84,566477.07,10801.40,124786.95,37082.13,209087.76,343.25,3322.00,422.37,1131.23,26660.81,308176.61,36.30,10.44,8.08,8.66,17.74,10.33,37.34,8.65

In [44]:
column_order = [
    "country",
    "year",

    "Number of fires",
    "EU Number of fires",
    "Italy share of EU fires (%)",

    "Burned hectares per year",
    "EU Burned hectares",
    "Italy share of EU burned hectares (%)",

    "natural_vegetation_ha",
    "EU Natural vegetation burned (ha)",
    "Italy share of EU natural vegetation burned (%)",

    "forests_ha",
    "EU Forests burned (ha)",
    "Italy share of EU forests burned (%)",

    "agricultural_areas_ha",
    "EU Agricultural areas burned (ha)",
    "Italy share of EU agricultural areas burned (%)",

    "artificial_surfaces_ha",
    "EU Artificial surfaces burned (ha)",
    "Italy share of EU artificial surfaces burned (%)",

    "other_land_cover_ha",
    "EU Other land cover burned (ha)",
    "Italy share of EU other land cover burned (%)",

    "natura2000_ha",
    "EU Natura 2000 burned (ha)",
    "Italy share of EU Natura 2000 burned (%)"
]

master_italy = master_italy[column_order]
master_italy

,country,year,Number of fires,EU Number of fires,Italy share of EU fires (%),Burned hectares per year,EU Burned hectares,Italy share of EU burned hectares (%),natural_vegetation_ha,EU Natural vegetation burned (ha),Italy share of EU natural vegetation burned (%),forests_ha,EU Forests burned (ha),Italy share of EU forests burned (%),agricultural_areas_ha,EU Agricultural areas burned (ha),Italy share of EU agricultural areas burned (%),artificial_surfaces_ha,EU Artificial surfaces burned (ha),Italy share of EU artificial surfaces burned (%),other_land_cover_ha,EU Other land cover burned (ha),Italy share of EU other land cover burned (%),natura2000_ha,EU Natura 2000 burned (ha),Italy share of EU Natura 2000 burned (%)
0,IT,2015,64,400,16.00,7689,144789,5.31,5133.52,104731.60,4.90,758.54,10145.69,7.48,1776.89,29423.95,6.04,20.04,434.50,4.61,0.00,53.30,0.00,2989.68,31038.95,9.63
1,IT,2016,144,719,20.03,35129,315657,11.13,11187.80,235380.39,4.75,5048.77,21816.71,23.14,18213.23,54803.86,33.23,164.21,2910.73,5.64,0.00,230.34,0.00,11094.20,79705.39,13.92
2,IT,2017,781,1709,45.70,137817,939059,14.68,69218.03,548710.99,12.61,36642.01,225847.34,16.22,30759.69,151823.93,20.26,1076.63,8443.98,12.75,120.60,4232.74,2.85,46843.81,191045.03,24.52
3,IT,2018,147,543,27.07,14650,110343,13.28,7418.21,61096.46,12.14,2684.04,35909.07,7.47,4349.51,11950.58,36.40,87.97,1146.86,7.67,110.27,240.05,45.94,3579.38,39845.13,8.98
4,IT,2019,400,874,45.77,32735,137145,23.87,17277.48,75855.84,22.78,3152.24,28372.53,11.11,12140.38,32077.21,37.85,128.66,587.19,21.91,36.28,252.32,14.38,8483.38,43781.66,19.38
5,IT,2020,1087,2319,46.87,60335,261180,23.10,30016.98,163598.03,18.35,9222.40,45953.86,20.07,20567.73,49718.32,41.37,316.24,1211.04,26.11,211.54,693.80,30.49,18078.94,88759.74,20.37
6,IT,2021,1348,2573,52.39,157193,408352,38.49,67298.03,184697.48,36.44,30610.87,99443.67,30.78,58233.24,120470.85,48.34,432.16,2911.69,14.84,616.68,790.32,78.03,34061.65,105327.59,32.34
7,IT,2022,1176,3482,33.77,62414,578953,10.78,30425.15,321577.83,9.46,11084.46,155218.89,7.14,20490.81,98060.56,20.90,319.69,3514.42,9.10,90.95,546.34,16.65,14899.72,215078.77,6.93
8,IT,2023,1231,2536,48.54,105121,379530,27.70,51144.97,190637.84,26.83,12972.93,99952.33,12.98,39034.26,84351.33,46.28,1273.38,3481.82,36.57,686.44,1077.61,63.70,30208.82,147135.68,20.53
9,IT,2024,1343,3506,38.31,48831,354387,13.78,24039.03,198396.75,12.12,8052.13,68333.95,11.78,16554.05,84640.21,19.56,129.58,2538.61,5.10,41.24,415.34,9.93,12841.11,113965.91,11.27
10,IT,2025,1717,4730,36.30,94456,904922,10.44,45781.84,566477.07,8.08,10801.40,124786.95,8.66,37082.13,209087.76,17.74,343.25,3322.00,10.33,422.37,1131.23,37.34,26660.81,308176.61,8.65

In [45]:
master_italy["Fires (% of Italy total)"] = (
    master_italy["Number of fires"]
    / master_italy["Number of fires"].sum()
    * 100
).round(2)

master_italy["Burned hectares (% of Italy total)"] = (
    master_italy["Burned hectares per year"]
    / master_italy["Burned hectares per year"].sum()
    * 100
).round(2)

master_italy["Natural vegetation (% of Italy total)"] = (
    master_italy["natural_vegetation_ha"]
    / master_italy["natural_vegetation_ha"].sum()
    * 100
).round(2)

master_italy["Forests (% of Italy total)"] = (
    master_italy["forests_ha"]
    / master_italy["forests_ha"].sum()
    * 100
).round(2)

master_italy["Agricultural areas (% of Italy total)"] = (
    master_italy["agricultural_areas_ha"]
    / master_italy["agricultural_areas_ha"].sum()
    * 100
).round(2)

master_italy["Artificial surfaces (% of Italy total)"] = (
    master_italy["artificial_surfaces_ha"]
    / master_italy["artificial_surfaces_ha"].sum()
    * 100
).round(2)

master_italy["Other land cover (% of Italy total)"] = (
    master_italy["other_land_cover_ha"]
    / master_italy["other_land_cover_ha"].sum()
    * 100
).round(2)

master_italy["Natura 2000 (% of Italy total)"] = (
    master_italy["natura2000_ha"]
    / master_italy["natura2000_ha"].sum()
    * 100
).round(2)

master_italy

,country,year,Number of fires,EU Number of fires,Italy share of EU fires (%),Burned hectares per year,EU Burned hectares,Italy share of EU burned hectares (%),natural_vegetation_ha,EU Natural vegetation burned (ha),Italy share of EU natural vegetation burned (%),forests_ha,EU Forests burned (ha),Italy share of EU forests burned (%),agricultural_areas_ha,EU Agricultural areas burned (ha),Italy share of EU agricultural areas burned (%),artificial_surfaces_ha,EU Artificial surfaces burned (ha),Italy share of EU artificial surfaces burned (%),other_land_cover_ha,EU Other land cover burned (ha),Italy share of EU other land cover burned (%),natura2000_ha,EU Natura 2000 burned (ha),Italy share of EU Natura 2000 burned (%),Fires (% of Italy total),Burned hectares (% of Italy total),Natural vegetation (% of Italy total),Forests (% of Italy total),Agricultural areas (% of Italy total),Artificial surfaces (% of Italy total),Other land cover (% of Italy total),Natura 2000 (% of Italy total)
0,IT,2015,64,400,16.00,7689,144789,5.31,5133.52,104731.60,4.90,758.54,10145.69,7.48,1776.89,29423.95,6.04,20.04,434.50,4.61,0.00,53.30,0.00,2989.68,31038.95,9.63,0.68,1.02,1.43,0.58,0.69,0.47,0.00,1.43
1,IT,2016,144,719,20.03,35129,315657,11.13,11187.80,235380.39,4.75,5048.77,21816.71,23.14,18213.23,54803.86,33.23,164.21,2910.73,5.64,0.00,230.34,0.00,11094.20,79705.39,13.92,1.53,4.64,3.12,3.85,7.03,3.83,0.00,5.29
2,IT,2017,781,1709,45.70,137817,939059,14.68,69218.03,548710.99,12.61,36642.01,225847.34,16.22,30759.69,151823.93,20.26,1076.63,8443.98,12.75,120.60,4232.74,2.85,46843.81,191045.03,24.52,8.28,18.22,19.28,27.96,11.87,25.09,5.16,22.33
3,IT,2018,147,543,27.07,14650,110343,13.28,7418.21,61096.46,12.14,2684.04,35909.07,7.47,4349.51,11950.58,36.40,87.97,1146.86,7.67,110.27,240.05,45.94,3579.38,39845.13,8.98,1.56,1.94,2.07,2.05,1.68,2.05,4.72,1.71
4,IT,2019,400,874,45.77,32735,137145,23.87,17277.48,75855.84,22.78,3152.24,28372.53,11.11,12140.38,32077.21,37.85,128.66,587.19,21.91,36.28,252.32,14.38,8483.38,43781.66,19.38,4.24,4.33,4.81,2.41,4.68,3.00,1.55,4.04
5,IT,2020,1087,2319,46.87,60335,261180,23.10,30016.98,163598.03,18.35,9222.40,45953.86,20.07,20567.73,49718.32,41.37,316.24,1211.04,26.11,211.54,693.80,30.49,18078.94,88759.74,20.37,11.52,7.98,8.36,7.04,7.94,7.37,9.05,8.62
6,IT,2021,1348,2573,52.39,157193,408352,38.49,67298.03,184697.48,36.44,30610.87,99443.67,30.78,58233.24,120470.85,48.34,432.16,2911.69,14.84,616.68,790.32,78.03,34061.65,105327.59,32.34,14.28,20.78,18.75,23.36,22.47,10.07,26.39,16.24
7,IT,2022,1176,3482,33.77,62414,578953,10.78,30425.15,321577.83,9.46,11084.46,155218.89,7.14,20490.81,98060.56,20.90,319.69,3514.42,9.10,90.95,546.34,16.65,14899.72,215078.77,6.93,12.46,8.25,8.48,8.46,7.91,7.45,3.89,7.10
8,IT,2023,1231,2536,48.54,105121,379530,27.70,51144.97,190637.84,26.83,12972.93,99952.33,12.98,39034.26,84351.33,46.28,1273.38,3481.82,36.57,686.44,1077.61,63.70,30208.82,147135.68,20.53,13.04,13.90,14.25,9.90,15.06,29.67,29.38,14.40
9,IT,2024,1343,3506,38.31,48831,354387,13.78,24039.03,198396.75,12.12,8052.13,68333.95,11.78,16554.05,84640.21,19.56,129.58,2538.61,5.10,41.24,415.34,9.93,12841.11,113965.91,11.27,14.23,6.46,6.70,6.15,6.39,3.02,1.77,6.12
10,IT,2025,1717,4730,36.30,94456,904922,10.44,45781.84,566477.07,8.08,10801.40,124786.95,8.66,37082.13,209087.76,17.74,343.25,3322.00,10.33,422.37,1131.23,37.34,26660.81,308176.61,8.65,18.19,12.49,12.75,8.24,14.31,8.00,18.08,12.71

In [46]:
column_order = [
    "country",
    "year",

    # Fires
    "Number of fires",
    "Fires (% of Italy total)",
    "EU Number of fires",
    "Italy share of EU fires (%)",

    # Total burned area
    "Burned hectares per year",
    "Burned hectares (% of Italy total)",
    "EU Burned hectares",
    "Italy share of EU burned hectares (%)",

    # Natural vegetation
    "natural_vegetation_ha",
    "Natural vegetation (% of Italy total)",
    "EU Natural vegetation burned (ha)",
    "Italy share of EU natural vegetation burned (%)",

    # Forests
    "forests_ha",
    "Forests (% of Italy total)",
    "EU Forests burned (ha)",
    "Italy share of EU forests burned (%)",

    # Agricultural areas
    "agricultural_areas_ha",
    "Agricultural areas (% of Italy total)",
    "EU Agricultural areas burned (ha)",
    "Italy share of EU agricultural areas burned (%)",

    # Artificial surfaces
    "artificial_surfaces_ha",
    "Artificial surfaces (% of Italy total)",
    "EU Artificial surfaces burned (ha)",
    "Italy share of EU artificial surfaces burned (%)",

    # Other land cover
    "other_land_cover_ha",
    "Other land cover (% of Italy total)",
    "EU Other land cover burned (ha)",
    "Italy share of EU other land cover burned (%)",

    # Natura 2000
    "natura2000_ha",
    "Natura 2000 (% of Italy total)",
    "EU Natura 2000 burned (ha)",
    "Italy share of EU Natura 2000 burned (%)"
]

master_italy = master_italy[column_order]
master_italy

,country,year,Number of fires,Fires (% of Italy total),EU Number of fires,Italy share of EU fires (%),Burned hectares per year,Burned hectares (% of Italy total),EU Burned hectares,Italy share of EU burned hectares (%),natural_vegetation_ha,Natural vegetation (% of Italy total),EU Natural vegetation burned (ha),Italy share of EU natural vegetation burned (%),forests_ha,Forests (% of Italy total),EU Forests burned (ha),Italy share of EU forests burned (%),agricultural_areas_ha,Agricultural areas (% of Italy total),EU Agricultural areas burned (ha),Italy share of EU agricultural areas burned (%),artificial_surfaces_ha,Artificial surfaces (% of Italy total),EU Artificial surfaces burned (ha),Italy share of EU artificial surfaces burned (%),other_land_cover_ha,Other land cover (% of Italy total),EU Other land cover burned (ha),Italy share of EU other land cover burned (%),natura2000_ha,Natura 2000 (% of Italy total),EU Natura 2000 burned (ha),Italy share of EU Natura 2000 burned (%)
0,IT,2015,64,0.68,400,16.00,7689,1.02,144789,5.31,5133.52,1.43,104731.60,4.90,758.54,0.58,10145.69,7.48,1776.89,0.69,29423.95,6.04,20.04,0.47,434.50,4.61,0.00,0.00,53.30,0.00,2989.68,1.43,31038.95,9.63
1,IT,2016,144,1.53,719,20.03,35129,4.64,315657,11.13,11187.80,3.12,235380.39,4.75,5048.77,3.85,21816.71,23.14,18213.23,7.03,54803.86,33.23,164.21,3.83,2910.73,5.64,0.00,0.00,230.34,0.00,11094.20,5.29,79705.39,13.92
2,IT,2017,781,8.28,1709,45.70,137817,18.22,939059,14.68,69218.03,19.28,548710.99,12.61,36642.01,27.96,225847.34,16.22,30759.69,11.87,151823.93,20.26,1076.63,25.09,8443.98,12.75,120.60,5.16,4232.74,2.85,46843.81,22.33,191045.03,24.52
3,IT,2018,147,1.56,543,27.07,14650,1.94,110343,13.28,7418.21,2.07,61096.46,12.14,2684.04,2.05,35909.07,7.47,4349.51,1.68,11950.58,36.40,87.97,2.05,1146.86,7.67,110.27,4.72,240.05,45.94,3579.38,1.71,39845.13,8.98
4,IT,2019,400,4.24,874,45.77,32735,4.33,137145,23.87,17277.48,4.81,75855.84,22.78,3152.24,2.41,28372.53,11.11,12140.38,4.68,32077.21,37.85,128.66,3.00,587.19,21.91,36.28,1.55,252.32,14.38,8483.38,4.04,43781.66,19.38
5,IT,2020,1087,11.52,2319,46.87,60335,7.98,261180,23.10,30016.98,8.36,163598.03,18.35,9222.40,7.04,45953.86,20.07,20567.73,7.94,49718.32,41.37,316.24,7.37,1211.04,26.11,211.54,9.05,693.80,30.49,18078.94,8.62,88759.74,20.37
6,IT,2021,1348,14.28,2573,52.39,157193,20.78,408352,38.49,67298.03,18.75,184697.48,36.44,30610.87,23.36,99443.67,30.78,58233.24,22.47,120470.85,48.34,432.16,10.07,2911.69,14.84,616.68,26.39,790.32,78.03,34061.65,16.24,105327.59,32.34
7,IT,2022,1176,12.46,3482,33.77,62414,8.25,578953,10.78,30425.15,8.48,321577.83,9.46,11084.46,8.46,155218.89,7.14,20490.81,7.91,98060.56,20.90,319.69,7.45,3514.42,9.10,90.95,3.89,546.34,16.65,14899.72,7.10,215078.77,6.93
8,IT,2023,1231,13.04,2536,48.54,105121,13.90,379530,27.70,51144.97,14.25,190637.84,26.83,12972.93,9.90,99952.33,12.98,39034.26,15.06,84351.33,46.28,1273.38,29.67,3481.82,36.57,686.44,29.38,1077.61,63.70,30208.82,14.40,147135.68,20.53
9,IT,2024,1343,14.23,3506,38.31,48831,6.46,354387,13.78,24039.03,6.70,198396.75,12.12,8052.13,6.15,68333.95,11.78,16554.05,6.39,84640.21,19.56,129.58,3.02,2538.61,5.10,41.24,1.77,415.34,9.93,12841.11,6.12,113965.91,11.27
10,IT,2025,1717,18.19,4730,36.30,94456,12.49,904922,10.44,45781.84,12.75,566477.07,8.08,10801.40,8.24,124786.95,8.66,37082.13,14.31,209087.76,17.74,343.25,8.00,3322.00,10.33,422.37,18.08,1131.23,37.34,26660.81,12.71,308176.61,8.65

In [47]:
master_italy = master_italy.round(2)

master_italy.to_excel(
    "master_italy_yearly.xlsx",
    index=False
)